version: '3.0'

services: 
    wizard:
        container_name: wizard
        build: 
            context: .
        env_file: 
        - .env
        volumes: 
        - .:/app
        - /app/node_modules
        ports:
        - 5000:5000 
        command: npm run dev
        # depends_on: 
        #     - mysql
        restart: always
    
    # mysql:
    #     container_name: mysql
    #     image: mysql
    #     env_file: 
    #         - .env
    #     environment:
    #        - MYSQL_ROOT_PASSWORD=12345678
    #        - MYSQL_DATABASE=wizardMed
    #     ports:
    #         - 8000:3306
    #     restart: always